### ISSUE TITLE
{name}

### ISSUE THREAD

**Issue by BoomScoom** [xxyy/commandblockerultimate#12]
Is there a way I can add something like {name} after a blocked command I've specified?  For example:
/tree fly {name} So that it will block it if there is any minecraft username where the {name} is.

**Comment by xxyy** [comment]
Currently not, no. Can't you just block all of /tree fly  ?

-- Above message was sent from my mobile phone. There may and will be all
kinds of errors included. For free!

**Comment by xxyy** [comment]
Um, just noticed, you can just block all of /tree. Should probably work
with my own code a bit more. Should improve that some time. Sorry for the
late reply by the way.

-- Above message was sent from my mobile phone. There may and will be all
kinds of errors included. For free!

**Comment by BoomScoom** [comment]
How do I block all of /tree then?

**Comment by xxyy** [comment]
Well, just add
````
  - tree
````
to blocked-commands (or something like that) in config.yml. Check if that
plugin offers a permission node first though.

-- Above message was sent from my mobile phone. There may and will be all
kinds of errors included. For free!

**Comment by xxyy** [comment]
Replaced by #24.
