### ISSUE TITLE
Invalid Config (Solved)

### ISSUE THREAD

**Issue by justin57754** [xxyy/commandblockerultimate#15]
I used the YAML checker and it said the config was fine

#  Command Blocker Ultimate config file
#  Get help at https://github.com/xxyy/commandblockerultimate/issues

# Define what commands should be blocked in the following property: (without leading slash)
# If you specify a command, its aliases will be blocked also. (Example: 'tell' will also block 'msg', 'bukkit:tell', etc.)
target-commands:
 - help
 - plugins
 - version
 - plugman load
 - plugman unload
 - plugman disable
 - plugman enable
 - ?
 - plugman
 - plugman check
 - plugman usage
 - plugman dump
 - plugman list
 - plugman info
 - plugman restart
 - plugman help
 - plugman reload

# Define the permission that a player needs to bypass the protection:
bypass-permission: cmdblock.bypass

# Should the plugin send an error message if one is not allowed to execute a command?
show-error-message: true

# What should that message be? (Use & for color codes, HTML escape codes accepted)
# Example: &c&lError message &euro;&auml;&#00A7;
error-message: '&4&lHCN Commands &c&l> &4Unknown command!'

# @since 1.02
# Whether to prevent tab-completion for blocked commands.
# Note: Requires ProtocolLib!
# Default value: true
prevent-tab: true

# What strategy to use when blocking tab-complete replies from the server.
# true: block all completions returning a targeted command (for example, if /p is typed and /pl is blocked, print error message)
# false: just remove blocked commands from list (in the above example, other commands starting with p would still be shown without notice)
# Default value: false
tab-restrictive-mode: false

**Comment by xxyy** [comment]
Hi, thanks for your report.

Please use pastebin.com for pasting configuration files next time.

I see some invalid characters in your config - specifically at "Example:
&c&lError message" and then a lot of weird symbols. Remove these symbols
and try again.

If that does not resolve your problem, upload the updated version of your
config to pastebin.com and also attach the exact error message displayed in
your server log.

-- Above message was sent from my mobile phone. There may and will be all
kinds of errors included.
