### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by davewanders** [xxyy/commandblockerultimate#17]
Hello,

I have found a bug.
You can block the command: /?
That doesn't work.

I hope you could fix this.

Kind Regards,
Dave Wanders

**Comment by xxyy** [comment]
Hi Dave,

thanks for your report. To block the /? command, you have to enclose it in
quotes in your config, like:

````
blocked-commands:
  - '?'
  - something_else
````

Please report back if it doesn't work.

-- Above message was sent from my mobile phone. There may and will be all
kinds of errors included.
