### ISSUE TITLE
Command Name

### ISSUE THREAD

**Issue by Malavent** [xxyy/commandblockerultimate#19]
Could it be a possibly flag to allow the blocked command in the feedback e.g "Sorry, {BlockedCmd} is disabled"

**Comment by xxyy** [comment]
Very good idea! Will implement as soon as I find time, but not before Friday. Thanks!

**Comment by Malavent** [comment]
Oh, i was thinking if you didn't mind, a feature (This is completely optional) that shows in chat like
" '{BlockedCmd}' is a blocked command, but since your an OP is has been executed "?

**Comment by xxyy** [comment]
I'll just test this and perform a 1.4.0 release shortly.

**Comment by xxyy** [comment]
Released as 1.4.1: https://github.com/xxyy/commandblockerultimate/releases/tag/cbu-parent-1.4.1
