### ISSUE TITLE
[Request] Tab-Complete Message Disable

### ISSUE THREAD

**Issue by WitherSkeletons** [xxyy/commandblockerultimate#25]
Removal or option to remove tab-complete denied message

**Comment by xxyy** [comment]
Set `show-error-message` to `false` in config.yml. Note that this also disables the message for blocked commands. https://github.com/xxyy/commandblockerultimate/blob/master/spigot/src/main/resources/config.yml#L15

**Comment by WitherSkeletons** [comment]
I know that, but I would like to have the command blocked message with the exemption of the tab complete message

**Comment by xxyy** [comment]
Fair enough. Will add this once I find time.

**Comment by WitherSkeletons** [comment]
Alright thanks a ton :D

**Comment by xxyy** [comment]
Added by 70ab267ff8982e79ac324bbf47d0dcba6740802a. That commit is included in the new 1.5.1 release available [here](https://www.spigotmc.org/resources/command-blocker-ultimate.296/update?update=115077). If there's any problems, feel free to reopen this issue or create a new one for unrelated problems.
