### ISSUE TITLE
NoSuchFieldException: commandMap with other plugins

### ISSUE THREAD

**Issue by m0bYczE** [xxyy/commandblockerultimate#28]
Hello i have this error´in bungee:
````
07:23:12 [SEVERE] java.lang.NoSuchFieldException: commandMap
07:23:12 [WARNING] [CommandBlockerUltimate] Could not get BungeeCord command map! That probably means that they changed their internals.Please open an issue at https://github.com/xxyy/commandblockerultimate/issues! Thank you!
07:23:12 [SEVERE]     at java.lang.Class.getDeclaredField(Class.java:2070)
07:23:12 [SEVERE]     at io.github.xxyy.cmdblocker.bungee.config.BungeeAliasResolver.stealCommandMap(BungeeAliasResolver.java:75)
07:23:12 [SEVERE]     at io.github.xxyy.cmdblocker.bungee.config.BungeeAliasResolver.refreshMap(BungeeAliasResolver.java:50)
07:23:12 [SEVERE]     at io.github.xxyy.cmdblocker.common.config.CBUConfig.resolveAliases(CBUConfig.java:156)
07:23:12 [SEVERE]     at io.github.xxyy.cmdblocker.bungee.CommandBlockerPlugin$1.run(CommandBlockerPlugin.java:66)
07:23:12 [SEVERE]     at net.md_5.bungee.scheduler.BungeeTask.run(BungeeTask.java:63)
07:23:12 [SEVERE]     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
07:23:12 [SEVERE]     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
07:23:12 [SEVERE]     at java.lang.Thread.run(Thread.java:745)
07:23:12 [WARNING] [CommandBlockerUltimate] This means that we can't get aliases for commands. Sorry for that!
07:23:12 [SEVERE] Task BungeeTask(sched=net.md_5.bungee.scheduler.BungeeScheduler@456d6c1e, id=288, owner=io.github.xxyy.cmdblocker.bungee.CommandBlockerPlugin@18275381, task=io.github.xxyy.cmdblocker.bungee.CommandBlockerPlugin$1@7134cb8f, delay=5000, period=0, running=true) encountered an exception
java.lang.ClassCastException: java.util.LinkedHashMap cannot be cast to java.lang.String
    at io.github.xxyy.cmdblocker.common.config.CBUConfig.resolveAliases(CBUConfig.java:159)
    at io.github.xxyy.cmdblocker.bungee.CommandBlockerPlugin$1.run(CommandBlockerPlugin.java:66)
    at net.md_5.bungee.scheduler.BungeeTask.run(BungeeTask.java:63)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
````

**Comment by xxyy** [comment]
Hi, which version of BungeeCord are you running?

**Comment by m0bYczE** [comment]
The newst Bungeecord 1211

**Comment by xxyy** [comment]
I'm sorry, I can't reproduce either error with BungeeCord 1211 and the latest CBU 1.5.1.  Try if the issue persists on a clan install. If it doesn't, update all your plugins and server software to their latest versions. If that doesn't help, try removing your plugins one-by-one to see which one could be the cause.

Are you using an official BungeeCord build from [md-5](http://ci.md-5.net/job/BungeeCord/)?

**Comment by xxyy** [comment]
The second issue may be caused by an invalid config file by the way. You might be able to resolve it by generating a new config file (delete the old one and reconfigure manually).

**Comment by m0bYczE** [comment]
I reseted the config, and this error: `19:20:35 [SEVERE] java.lang.NoSuchFieldException: commandMap
19:20:35 [WARNING] [CommandBlockerUltimate] Could not get BungeeCord command map! That probably means that they changed their internals.Please open an issue at https://github.com/xxyy/commandblockerultimate/issues! Thank you!
19:20:35 [SEVERE]     at java.lang.Class.getDeclaredField(Class.java:2070)
19:20:35 [WARNING] [CommandBlockerUltimate] This means that we can't get aliases for commands. Sorry for that!
19:20:35 [SEVERE]     at io.github.xxyy.cmdblocker.bungee.config.BungeeAliasResolver.stealCommandMap(BungeeAliasResolver.java:75)
19:20:35 [SEVERE]     at io.github.xxyy.cmdblocker.bungee.config.BungeeAliasResolver.refreshMap(BungeeAliasResolver.java:50)
19:20:35 [SEVERE]     at io.github.xxyy.cmdblocker.common.config.CBUConfig.resolveAliases(CBUConfig.java:156)
19:20:35 [SEVERE]     at io.github.xxyy.cmdblocker.bungee.CommandBlockerPlugin$1.run(CommandBlockerPlugin.java:66)
19:20:35 [SEVERE]     at net.md_5.bungee.scheduler.BungeeTask.run(BungeeTask.java:63)
19:20:35 [SEVERE]     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
19:20:35 [SEVERE]     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
19:20:35 [SEVERE]     at java.lang.Thread.run(Thread.java:745)
`

**Comment by xxyy** [comment]
This means that the second issue was caused by your configuration file. Now for the actual issue with the command map. 

As I said, I cannot reproduce that with the latest BungeeCord and CBU versions.

Please provide the following information that could help with diagnosing this further:

1. CBU version
2. Are you using a custom build of BungeeCord?
3. BungeeCord plugins and version numbers
4. Complete BungeeCord startup log (the log from the beginning to the line where it says `Listening on (your ip)`

**Comment by xxyy** [comment]
Hi, is this still an issue for you? If so, please provide the information requested above.

**Comment by xxyy** [comment]
Assuming that this is fixed since there hasn't been a reply for a month now. Please reopen if this is still an issue.

**Comment by m0bYczE** [comment]
Yes it's still bug!

**Comment by xxyy** [comment]
As I said, I cannot reproduce that with the latest BungeeCord and CBU versions.

Please provide the following information that could help with diagnosing this further:

1. CBU version
2. Are you using a custom build of BungeeCord?
3. BungeeCord plugins and version numbers
4. Complete BungeeCord startup log (the log from the beginning to the line where it says `Listening on (your ip)`

**Comment by m0bYczE** [comment]
I'm using CBU 1.5.1. I have now bungeecord alternative Waterfall, but it have same classes (if i mean good). 
Code (with plugins and all): `20:16:27 [INFO] Using OpenSSL based native cipher.
20:16:27 [INFO] Using native code compressor
20:16:27 [INFO] Enabled Waterfall version git:Waterfall-Bootstrap:1.11-SNAPSHOT:a8a855c:100
20:16:28 [INFO] Not on Windows, attempting to use enhanced EpollEventLoop
20:16:28 [INFO] Epoll is working, utilising it!
20:16:28 [INFO] Discovered module: ModuleSpec(name=cmd_alert, file=modules/cmd_alert.jar, provider=JenkinsModuleSource())
20:16:28 [INFO] Discovered module: ModuleSpec(name=cmd_find, file=modules/cmd_find.jar, provider=JenkinsModuleSource())
20:16:28 [INFO] Discovered module: ModuleSpec(name=cmd_list, file=modules/cmd_list.jar, provider=JenkinsModuleSource())
20:16:28 [INFO] Discovered module: ModuleSpec(name=cmd_send, file=modules/cmd_send.jar, provider=JenkinsModuleSource())
20:16:28 [INFO] Discovered module: ModuleSpec(name=cmd_server, file=modules/cmd_server.jar, provider=JenkinsModuleSource())
20:16:28 [INFO] Discovered module: ModuleSpec(name=reconnect_yaml, file=modules/reconnect_yaml.jar, provider=JenkinsModuleSource())
20:16:28 [INFO] Loaded plugin BungeeReload version v0.1 by Leftwitch
20:16:28 [INFO] Loaded plugin LiteAnnouncer version 2.4 by LiteFine
20:16:28 [INFO] Loaded plugin reconnect_yaml version git:reconnect_yaml:1.11-SNAPSHOT:a8a855c:100 by WaterfallMC
20:16:28 [INFO] Loaded plugin BungeeWhiteList version 1.0 by xGabryMC
20:16:28 [INFO] Loaded plugin SkinsRestorer version 12.9.7 by Blackfire62, Th3Tr0LLeR
20:16:28 [INFO] Loaded plugin Yamler version 2.4.0-SNAPSHOTb-16 by geNAZt
20:16:28 [INFO] Loaded plugin CommandBlockerUltimate version 1.5.1 by xxyy
20:16:28 [INFO] Loaded plugin GMBungee version 1.0 by m0bY_czE
20:16:28 [INFO] Loaded plugin BungeeAliases version 1.1.3 by L4BORG
20:16:28 [INFO] Loaded plugin NuVotifier version 2.3.3 by blakeman8192, Kramer, tuxed
20:16:28 [INFO] Loaded plugin BungeePluginManager version 1.0 by _Shevchik_
20:16:28 [INFO] Loaded plugin PermissionsCord version 1.1.6 by NESlover
20:16:28 [INFO] Loaded plugin cmd_list version git:cmd_list:1.11-SNAPSHOT:a8a855c:100 by WaterfallMC
20:16:28 [INFO] Loaded plugin cmd_find version git:cmd_find:1.11-SNAPSHOT:a8a855c:100 by WaterfallMC
20:16:28 [INFO] Loaded plugin AuthMeBridge version 1.0 by CryLegend
20:16:28 [INFO] Loaded plugin cmd_server version git:cmd_server:1.11-SNAPSHOT:a8a855c:100 by WaterfallMC
20:16:28 [INFO] Loaded plugin PvPer-Report version 1.0 by Raytex
20:16:28 [INFO] Loaded plugin cmd_alert version git:cmd_alert:1.11-SNAPSHOT:a8a855c:100 by WaterfallMC
20:16:28 [INFO] Loaded plugin cmd_send version git:cmd_send:1.11-SNAPSHOT:a8a855c:100 by WaterfallMC
20:16:28 [WARNING] Forced host server pvp is not defined
20:16:28 [INFO] Enabled plugin BungeeReload version v0.1 by Leftwitch
20:16:28 [INFO] [LiteAnnouncer] Plugin enabled. Version: 2.4. Plugin made special for PixelFine Network.
20:16:28 [INFO] Enabled plugin LiteAnnouncer version 2.4 by LiteFine
20:16:28 [INFO] Enabled plugin reconnect_yaml version git:reconnect_yaml:1.11-SNAPSHOT:a8a855c:100 by WaterfallMC
20:16:28 [INFO] Enabled plugin BungeeWhiteList version 1.0 by xGabryMC
20:16:28 [INFO] Enabled plugin SkinsRestorer version 12.9.7 by Blackfire62, Th3Tr0LLeR
20:16:28 [INFO] Enabled plugin Yamler version 2.4.0-SNAPSHOTb-16 by geNAZt
20:16:28 [INFO] [CommandBlockerUltimate] CommandBlockerUltimate null Version null Build null is licensed under the GNU General Public License Version 2. See the LICENSE file included in its .jar archive for details.
20:16:28 [INFO] Enabled plugin CommandBlockerUltimate version 1.5.1 by xxyy
20:16:28 [INFO] Enabled plugin GMBungee version 1.0 by m0bY_czE
20:16:28 [INFO] Enabled plugin BungeeAliases version 1.1.3 by L4BORG
20:16:28 [INFO] [NuVotifier] Loaded token for website: default
20:16:28 [INFO] [NuVotifier] Loaded token for website: survival
20:16:28 [INFO] 
20:16:28 [INFO] §a    +===============+
20:16:28 [INFO] §a    | SkinsRestorer |
20:16:28 [INFO] §a    +===============+
20:16:28 [INFO] 
20:16:28 [INFO] §a    STABLE BUILD
20:16:28 [INFO] 
20:16:28 [INFO] §b    Current version: §a12.9.7
20:16:28 [INFO] §a    The latest version!
20:16:28 [INFO] 
20:16:28 [INFO] [NuVotifier] Method none selected for vote forwarding: Votes will not be forwarded to backend servers.
20:16:28 [INFO] Enabled plugin NuVotifier version 2.3.3 by blakeman8192, Kramer, tuxed
20:16:28 [INFO] Enabled plugin BungeePluginManager version 1.0 by _Shevchik_
20:16:28 [INFO] [NuVotifier] Votifier enabled on socket /127.0.0.1:51234.
20:16:29 [INFO] Enabled plugin PermissionsCord version 1.1.6 by NESlover
20:16:29 [INFO] Enabled plugin cmd_list version git:cmd_list:1.11-SNAPSHOT:a8a855c:100 by WaterfallMC
20:16:29 [INFO] Enabled plugin cmd_find version git:cmd_find:1.11-SNAPSHOT:a8a855c:100 by WaterfallMC
20:16:29 [INFO] Enabled plugin AuthMeBridge version 1.0 by CryLegend
20:16:29 [INFO] Enabled plugin cmd_server version git:cmd_server:1.11-SNAPSHOT:a8a855c:100 by WaterfallMC
20:16:29 [INFO] Enabled plugin PvPer-Report version 1.0 by Raytex
20:16:29 [INFO] Enabled plugin cmd_alert version git:cmd_alert:1.11-SNAPSHOT:a8a855c:100 by WaterfallMC
20:16:29 [INFO] Enabled plugin cmd_send version git:cmd_send:1.11-SNAPSHOT:a8a855c:100 by WaterfallMC
20:16:29 [INFO] Listening on /0.0.0.0:25565
20:16:29 [INFO] Started query on /0.0.0.0:25565
20:16:33 [SEVERE] java.lang.NoSuchFieldException: commandMap
20:16:33 [WARNING] [CommandBlockerUltimate] Could not get BungeeCord command map! That probably means that they changed their internals.Please open an issue at https://github.com/xxyy/commandblockerultimate/issues! Thank you!
20:16:33 [SEVERE] 	at java.lang.Class.getDeclaredField(Class.java:2070)
20:16:33 [WARNING] [CommandBlockerUltimate] This means that we can't get aliases for commands. Sorry for that!
20:16:33 [SEVERE] 	at io.github.xxyy.cmdblocker.bungee.config.BungeeAliasResolver.stealCommandMap(BungeeAliasResolver.java:75)
20:16:33 [SEVERE] 	at io.github.xxyy.cmdblocker.bungee.config.BungeeAliasResolver.refreshMap(BungeeAliasResolver.java:50)
20:16:33 [SEVERE] 	at io.github.xxyy.cmdblocker.common.config.CBUConfig.resolveAliases(CBUConfig.java:156)
20:16:33 [SEVERE] 	at io.github.xxyy.cmdblocker.bungee.CommandBlockerPlugin$1.run(CommandBlockerPlugin.java:66)
20:16:33 [SEVERE] 	at net.md_5.bungee.scheduler.BungeeTask.run(BungeeTask.java:63)
20:16:33 [SEVERE] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
20:16:33 [SEVERE] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
20:16:33 [SEVERE] 	at java.lang.Thread.run(Thread.java:745)`

**Comment by xxyy** [comment]
You seem to have a whole lot of plugins. Please try to remove **all** plugins and then see if the issue is still there. If it's not, try adding your plugins one-by-one and report back which one was causing the issue and I might be able to fix it.

CBU should generally be compatible with Waterfall.

**Comment by m0bYczE** [comment]
Problem fixed, i reinstall all plugin :D Thanks.
