### ISSUE TITLE
Bungee dont works

### ISSUE THREAD

**Issue by ArtutoGamerYT** [xxyy/commandblockerultimate#30]
24.02 15:06:46 [Server] INFO Your configuration file is invalid! See the server log for more details.Maybe http://yaml-online-parser.appspot.com/ can help you diagnose your issue.If not, you can get help at https://github.com/xxyy/commandblockerultimate/issues
24.02 15:06:46 [Server] SEVERE at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)
24.02 15:06:46 [Server] SEVERE at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:62)
24.02 15:06:46 [Server] SEVERE at net.md_5.bungee.api.plugin.PluginManager.dispatchCommand(PluginManager.java:116)
24.02 15:06:46 [Server] SEVERE at net.md_5.bungee.api.plugin.PluginManager.dispatchCommand(PluginManager.java:169)
24.02 15:06:46 [Server] SEVERE at io.github.xxyy.cmdblocker.bungee.command.CommandGCBU.execute(CommandGCBU.java:52)
24.02 15:06:46 [Server] SEVERE at io.github.xxyy.cmdblocker.bungee.command.CommandGCBU.handleReloadConfig(CommandGCBU.java:65)
24.02 15:06:46 [Server] SEVERE at io.github.xxyy.cmdblocker.bungee.CommandBlockerPlugin.replaceConfigAdapter(CommandBlockerPlugin.java:177)
24.02 15:06:46 [Server] SEVERE at io.github.xxyy.cmdblocker.common.config.CBUConfig.resolveAliases(CBUConfig.java:161)
24.02 15:06:46 [Server] SEVERE at io.github.xxyy.cmdblocker.bungee.config.BungeeAliasResolver.resolve(BungeeAliasResolver.java:67)
24.02 15:06:46 [Server] SEVERE at java.util.AbstractList.add(AbstractList.java:108)
24.02 15:06:46 [Server] SEVERE at java.util.AbstractList.add(AbstractList.java:148)
24.02 15:06:46 [Server] SEVERE java.lang.UnsupportedOperationException
24.02 15:06:46 [Server] INFO CONSOLE executed command: /gcbu reloadcfg

Read down to up

**Comment by xxyy** [comment]
>INFO Your configuration file is invalid! See the server log for more
details.Maybe http://yaml-online-parser.appspot.com/ can help you diagnose
your issue.

If you're unable to resolve the issue by yourself, please paste your
configuration file (plugins/CommandBlockerUltimate/config.yml) to
https://pastebin.com/ and provide the link here.

You can also try deleting the file (make a backup first!) and starting from
scratch.

**Comment by ArtutoGamerYT** [comment]
I checked it with http://yaml-online-parser.appspot.com/ and works

**Comment by xxyy** [comment]
If you're unable to resolve the issue by yourself, please paste your
configuration file (plugins/CommandBlockerUltimate/config.yml) to
https://pastebin.com/ and provide the link here.

You can also try deleting the file (make a backup first!) and starting from
scratch.

**Comment by xxyy** [comment]
Okay, actually, my bad, I overlooked an important detail in the error message. Your file is probably valid. I'll take a look.

**Comment by ArtutoGamerYT** [comment]
http://pastebin.com/GDJpMgpv

**Comment by xxyy** [comment]
Try this build: https://ci.l1t.li/job/public~cmdblkult/55/

**Comment by ArtutoGamerYT** [comment]
okay I will try it

**Comment by ArtutoGamerYT** [comment]
Fixed

**Comment by xxyy** [comment]
Thanks a lot for your report! I have released the fix as [version 1.5.2](https://j.l1t.li/cmdblk).
