### ISSUE TITLE
Proceed commands silently. Disable command responses in text chat.

### ISSUE THREAD

**Issue by Chenguang1** [xxyy/commandblockerultimate#31]
Hello! Could you please tell me how can I disable not commands but RESPONSES to them in a text chat. What I mean is I don't want to block commands. I just don't want to see game notifications that my commands were performed.
Let's say if I type "/time set day" I don't want to see response message "set the time to 1000" in a text chat.
If I type "/toggledownfall" I don't want to see "toggled downfall" in a text chat. I just want my commands proceed silently. Without any notifications in my text chat.

**Comment by xxyy** [comment]
Hi!
The feature you're requesting is sadly not a trivial thing at all. It is not possible to accomplish this via the API - there is no way to tell which plugin sent a particular chat message or why.

As a hack, one could theoretically block the first message that goes to the executing player after a command execution, but this might result in weird behaviour. The best way to accomplish what you want to do is to modify the plugins that send the messages. For most plugins, however, I doubt that the authors will acknowledge the need for such a feature.

**Comment by Chenguang1** [comment]
Thanks for your feedback.
