### ISSUE TITLE
Players can still use blocked commands ¯\_(ツ)_/¯ 

### ISSUE THREAD

**Issue by Skelebabe** [xxyy/commandblockerultimate#46]
[//]: # ( This line a comment and will not be shown in the final report )
Can’t figure out what I’ve done wrong.
[command blocker ultimate.pdf](https://github.com/xxyy/commandblockerultimate/files/1887864/command.blocker.ultimate.pdf)

FYI this is the latest version of Spigot

**Comment by xxyy** [comment]
Hi, sorry, but the plugin doesn't currently support blocking of sub
commands. Your 'mv remove' won't work. You can only block the whole mv
command.

If that is not the issue, please make sure that the players you're testing
with don't have the bypass permission, cmdblock.bypass by default.

**Comment by Skelebabe** [comment]
Okay.
But would that one command negate the others?
We’ve been testing the ‘kick’ command and it can still be used even without the bypass command.
How would they have that command by default?

Is it not a command they have to use before the blocked commands?

**Comment by xxyy** [comment]
You're entirely right, it wouldn't affect the other commands. What platform
are you on, BungeeCord or Spigot? What server and plugin version? You can
turn on notify-bypass to make sure it's not the permissions.

**Comment by Skelebabe** [comment]
It’s the latest ver/build of spigot.
The plug in is v1.5.5

**Comment by Skelebabe** [comment]
Still not working.
How do you restrict users from having default permissions?

**Comment by xxyy** [comment]
Thanks for the versions. So the players are getting the bypass message and
the permission is the issue? It really depends on the permissions plugin
you're using.

**Comment by Skelebabe** [comment]
Yes. It says, this is blocked but since you have permission I’ll do it anyway (or something like that).
So it recognizes it’s blocked but everyone seems to have permission.

**Comment by Skelebabe** [comment]
I’m not using any specific permissions plugin. Trying to control other plugins that have their own OP permissions.
Like Skywars.
All players on server have level 2 OP (no player management). Only one is level 4 (everything)
Should I make them all level 1?

Sorry. I don’t play the game. I’m just the tech for my kids’ server.🙄

**Comment by Skelebabe** [comment]
Cool, thanks! I’ll look into this!🤘
